local util = require("onedarkpro.lib.color")

describe("Using the theme", function()
    before_each(function()
        vim.cmd(":e tests/stubs/test.txt")
    end)

    it("it should be able to darken colors", function()
        local dark_red = util.darken("#ff0000", 0.5)
        assert.equals("#800000", string.lower(dark_red))
    end)
    it("it should be able to darken colors", function()
        local light_red = util.lighten("#ff0000", 0.5)
        assert.equals("#ff8080", string.lower(light_red))
    end)
end)
