name: General (non bug) issue
description: For general issues, questions or enhancements. NOT for bugs or configuration issues
assignees: olimorris

body:
    - type: markdown
      attributes:
        value: |
          > **Note:** Please do not use this template if you are having issues using the plugin. We have a dedicated issue template specifically for that purpose.

    - type: textarea
      id: description
      attributes:
        label: Issue/Question/Enhancement
        description: Please include the detail of your issue below
        placeholder: Your issue
      validations:
        required: true

